name: google_ml_kit_example
description: Demonstrates how to use the google_ml_kit plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+3
  camera: ^0.10.4
  path: ^1.8.2
  path_provider: ^2.0.14
  google_mlkit_commons: ^0.3.0
  google_mlkit_smart_reply: ^0.6.0
  google_mlkit_barcode_scanning: ^0.6.0
  google_mlkit_digital_ink_recognition: ^0.7.0
  google_mlkit_face_detection: ^0.6.0
  google_mlkit_image_labeling: ^0.6.0
  google_mlkit_object_detection: ^0.7.0
  google_mlkit_pose_detection: ^0.6.0
  google_mlkit_selfie_segmentation: ^0.3.0
  google_mlkit_text_recognition: ^0.6.0
  google_mlkit_entity_extraction: ^0.7.0
  google_mlkit_language_id: ^0.6.0
  google_mlkit_translation: ^0.6.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ml/
